### ISSUE TITLE
[BUG] Center hud dead not centered

### ISSUE THREAD

**Issue by qawery-just-sad** [olokos/Surftimer-olokos#102]
**Describe the bug**
Center Hud Dead is justified to left

**Expected behavior**
Center Hud Dead is justified to the center

**Screenshots**
![image](https://user-images.githubusercontent.com/53490397/81064890-c35eb500-8eda-11ea-98b3-eddbe00ffde8.png)

**Plugin List**
Latest dev on @olokos  server

**Additional context**
nope

**Comment by PwnK** [comment]
I also noticed center hud dead justified to left like in the picture in my server and apparently it has been like that for months and no one has complained.

https://github.com/olokos/Surftimer-olokos/blob/7d2b6cafa59977fb5ca3961cb0ac58cb16233469/addons/sourcemod/scripting/surftimer/misc.sp#L4909

Looks like this is caused by changing '\n' to ' ' here. Strange that it only happens in center hud dead and this is the way it is done also in https://github.com/Franc1sco/FixHintColorMessages

Changing it back to '\n' should be fine and wouldn't bring #91 back.

**Comment by Bara** [comment]
@PwnK if you can confirm this, I would change this in the dev branch.

**Comment by olokos** [comment]
#91 #92 
are related to this issue.
