### ISSUE TITLE
[BUG] Replay Bots (Enum Structs Branch)

### ISSUE THREAD

**Issue by MestroGroup** [olokos/Surftimer-olokos#28]
**Describe the bug**
Replay bots can't load from a pre-recorded file.

**Additional context**
```
[SM] Exception reported: Invalid Handle 0 (error: 4)
[SM] Blaming: surftimer.smx
[SM] Call stack trace:
[SM]   [0] PushArrayArray
[SM]   [1] Line 644, surftimer/replay.sp::LoadRecordFromFile
[SM]   [2] Line 432, surftimer/replay.sp::PlayRecord
[SM]   [3] Line 721, surftimer/replay.sp::LoadRecordReplay
[SM]   [4] Line 683, surftimer/replay.sp::RefreshBot
```

SM 1.11, MM 1.11.

**Comment by thorfriis** [comment]
Ive got this one too!
`L 04/17/2020 - 16:21:02: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 04/17/2020 - 16:21:02: [SM] Blaming: SurfTimer.smx
L 04/17/2020 - 16:21:02: [SM] Call stack trace:
L 04/17/2020 - 16:21:02: [SM]   [0] PushArrayArray
L 04/17/2020 - 16:21:02: [SM]   [1] Line 644, surftimer/replay.sp::LoadRecordFromFile
L 04/17/2020 - 16:21:02: [SM]   [2] Line 432, surftimer/replay.sp::PlayRecord
L 04/17/2020 - 16:21:02: [SM]   [3] Line 721, surftimer/replay.sp::LoadRecordReplay
L 04/17/2020 - 16:21:02: [SM]   [4] Line 683, surftimer/replay.sp::RefreshBot:
`

**Comment by olokos** [comment]
I am sorry guys, but unfortunately SM1.11 is unsupported it seems.

We're currently going through lots of issues and we're hitting them strong with each hour, but we cannot allow ourselves to rely on unstable sourcemod, which has unstable changes to it and can potentially cause bugs completely unrelated to the code of surftimer.

I am not saying those issues are caused by sourcemod, but I am not denying it either.
It's just too hard to tell at the current level of complexity.

I will update the readme shortly!

**Comment by sneak-it** [comment]
Just a follow-up, this does not mean that the error stems from having 1.11 installed, it could be an issue introduced in the enum-structs branch.

**Comment by thorfriis** [comment]
It is probably the enum-structs branch, as i am using SM 1.10

**Comment by Bara** [comment]
That's the branch and not SM1.11. So using SM1.11 should be fine.
