### ISSUE TITLE
[BUG] f on center Hud latest Dev branch

### ISSUE THREAD

**Issue by Caaine** [olokos/Surftimer-olokos#91]
**Screenshots**
https://cdn.discordapp.com/attachments/425362754959048726/706101252794220544/unknown.png

latest Dev branch

**Comment by olokos** [comment]
![Fixed image](https://i.imgur.com/WLx14sd.png)
Reuploaded the image, in case it wouldn't work for somebody
I confirm this bug, but not sure where it appeared exactly.

Those are recent commits that changed Center hud, but I cannot see where the issue is:
91e87b335bffd8e146967f64c0f2ed7fbff1c72c
00e53b0195c2f99f5ea8cb445c792b8d8e7fbd83
57d58f2d4fdbb09f5805a05fc9a5e7b8528ed958

**Comment by qawery-just-sad** [comment]
wild guess don't terminate printcsgohud

**Comment by PwnK** [comment]
Can someone on dev branch try reverting those commits one by one?

It would be really weird if it was my commit causing it because it doesn't add 'f' characters anywhere but just sets the last index of buff [sizeof(buff) - 1] to '\0'

**Comment by qawery-just-sad** [comment]
well i did and yes it's your commit and if u look at https://github.com/olokos/Surftimer-olokos/blob/ef94956ba90852dd2a0c3b7eb31ad7102b7abc9f/addons/sourcemod/scripting/surftimer/misc.sp#L4915 there are null terminations already
